import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot box-and-whisker chart of model accuracies per field"
    )
    parser.add_argument(
        "--input_csv",
        type=str,
        default="output/accuracy_per_field.csv",
        help="CSV generated by accuracy_per_field.py",
    )
    parser.add_argument(
        "--output_svg",
        type=str,
        default="output/accuracy_per_field_histogram.svg",
        help="Output SVG path",
    )
    parser.add_argument(
        "--exclude-model",
        type=str,
        default="Qwen_Qwen3-VL-30B-A3B-Instruct",
        help="Exact model name to exclude from aggregation",
    )
    args = parser.parse_args()

    rows = []
    with open(args.input_csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("group") != "model":
                continue
            entity = row.get("entity", "")
            if entity == args.exclude_model or "30B-A3B" in entity:
                continue
            rows.append(
                {
                    "group": row.get("group", ""),
                    "entity": entity,
                    "field": row.get("field", ""),
                    "accuracy": float(row.get("accuracy", 0.0)),
                }
            )

    if not rows:
        raise RuntimeError("No rows available for plotting")

    field_order = [
        ("overbite", "Overbite"),
        ("crowding", "Crowding"),
        ("molar_left", "Occl. Molar L."),
        ("molar_right", "Occl. Molar R."),
        ("canine_left", "Occl. Canine L."),
        ("canine_right", "Occl. Canine R."),
        ("curve_spee", "Spee Curve"),
        ("curve_wilson", "Wilson Curve"),
        ("midlines", "Midlines"),
        ("transverse", "Transverse"),
        ("missing_teeth", "Missing Teeth"),
    ]

    values_by_field = {k: [] for k, _ in field_order}
    for r in rows:
        if r["field"] in values_by_field:
            values_by_field[r["field"]].append(float(r["accuracy"]))

    labels = []
    data = []
    for field_key, field_label in field_order:
        vals = np.array(values_by_field.get(field_key, []), dtype=float)
        if vals.size == 0:
            continue
        labels.append(field_label)
        data.append(vals)

    if not data:
        raise RuntimeError("No model data available after filtering")

    fig, ax = plt.subplots(figsize=(18, 8))
    bp = ax.boxplot(
        data,
        positions=np.arange(1, len(data) + 1),
        widths=0.55,
        patch_artist=True,
        showmeans=True,
        meanline=True,
        whis=(0, 100),
    )

    for box in bp["boxes"]:
        box.set_facecolor("#7fb3d5")
        box.set_edgecolor("#2f4f4f")
        box.set_alpha(0.8)
        box.set_linewidth(1.8)

    for whisker in bp["whiskers"]:
        whisker.set_color("#2f4f4f")
        whisker.set_linewidth(1.6)

    for cap in bp["caps"]:
        cap.set_color("#2f4f4f")
        cap.set_linewidth(1.6)

    for median in bp["medians"]:
        median.set_color("#1b2631")
        median.set_linewidth(2.1)

    for mean in bp["means"]:
        mean.set_color("#c0392b")
        mean.set_linewidth(1.8)

    ax.set_title("")
    ax.set_ylabel("Accuracy", fontsize=20)
    ax.set_xlabel("")
    ax.set_ylim(0.0, 1.0)
    ax.set_xticks(np.arange(1, len(labels) + 1))
    ax.set_xticklabels([])
    for i, label in enumerate(labels, start=1):
        ax.text(
            i,
            0.01,
            label,
            rotation=90,
            ha="center",
            va="bottom",
            fontsize=20,
            fontweight="black",
            color="#1b2631",
            clip_on=True,
            bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none", "pad": 1.5},
        )
    ax.tick_params(axis="y", labelsize=18)
    ax.grid(axis="y", linestyle="--", alpha=0.25)
    fig.tight_layout()

    output_svg = Path(args.output_svg)
    output_svg.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_svg, dpi=220)
    plt.close(fig)
    print(f"Saved plot to: {output_svg}")


if __name__ == "__main__":
    main()
