seed: 42

wandb_project: "ios-classification"
run_name: "PointTransformer_32k_384_improv_bs32_gamma_3_384tk_final_AttnPool"

data:
  dataset_path: "/work/grana_maxillo/IOS-DraftReport/_data/Dataset_FerraraDump_400_and_Bits2Bites"
  classification_path: "/work/grana_maxillo/IOS-DraftReport/src/auto-captioning/task_classes"
  schema_path: "/work/grana_maxillo/IOS-DraftReport/_data/multi_task_classification.json"
  num_points: 32768

model:
  encoder:
    trans_dim: 384
    depth: 12
    num_heads: 6
    encoder_dims: 384
    group_size: 32
    num_group: 512
    drop_path_rate: 0.1
    output_dim: 384
    projection_dropout: 0.1

training:
  num_epochs: 200
  batch_size: 32
  learning_rate: 0.0001
  warmup_epochs: 25
  weight_decay: 0.001
  max_grad_norm: 1.0
  focal_gamma: 3.0
  num_workers: 4
  gradient_accumulation_steps: 1

logging:
  log_interval: 10
  save_interval: 5
  checkpoint_dir: "/work/grana_maxillo/IOS-DraftReport/outputs/classification_checkpoints"
